Ver 1.0
MVBelyaev78/SkyPro_Java_Homework_2024-11-11 pull request #1
Opened 2024-12-02 15:23 UTC by MVBelyaev78

Task complete.

2024-12-03 15:18 UTC, isavinov requested changes

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/controller/DepartmentController.java
> +    private final Department department = new Department(TestDepartment.createData());
Нарушение принципа DI. Зависимости в контроллер (как и в любой спринговый бин) должны передаваться спрингом (желательно через конструктор)

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +public class Department {
Нарушения нейминга - Этот код описывает не департамент, а логику работы на сотрудниками департамента. Обычно использует название DepartmentService

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +        this.arrEmployee = arrEmployee;
Это лишнее, спринг сюда пустой лист передаст, так как нет такого бина

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +    public boolean equals(Object object) {
Метод equals пишется для классов с данными, а не с логикой

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +    public int hashCode() {
Аналогично с методом hashCode

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +        if (resultOptional.isPresent()) {
Второй стрим не нужен. Сотрудника с самой низкой/высокой зарплатой можно найти за один прогон стрима

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +    public List<Employee> getLowestPaidEmployee(int codeDepartment) {
Второй стрим не нужен. Сотрудника с самой низкой/высокой зарплатой можно найти за один прогон стрима

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +    public List<Employee> getHighestPaidEmployee() {
Второй стрим не нужен. Сотрудника с самой низкой/высокой зарплатой можно найти за один прогон стрима

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +    public List<Employee> getHighestPaidEmployee(int codeDepartment) {
Второй стрим не нужен. Сотрудника с самой низкой/высокой зарплатой можно найти за один прогон стрима

2024-12-03 15:18 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +                .sorted(Comparator.comparing(Employee::getCodeDepartment).thenComparing(Employee::getFullName))
По условию - сотрудников с разделением по отделам. Тут нет разделения, тут сортировка. Собирать стоит в мапу, где ключ - департамент, значение - коллекция сотрудников этого департамента

2024-12-03 23:23 UTC, MVBelyaev78 commented on src/main/java/pro/sky/hw_2024_11_11/controller/DepartmentController.java
> +    private final Department department = new Department(TestDepartment.createData());
В таком случае откуда должен вызываться метод TestDepartment.createData()? Просмотрел на примерах (правда, на скорую руку, признаюсь) принцип использования DI через конструктор, но объяснений, как вызывать методы, наполняющие контроллер данными, не нашел. Копать в сторону @Repository или куда-то еще?

2024-12-03 23:28 UTC, MVBelyaev78 commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +        if (resultOptional.isPresent()) {
Признаюсь: не понимаю, как это сделать. Не подскажешь, в сторону каких операций копать? Предположу, что здесь надо как-то надо map применить, чтобы схлопнуть Employee::getSalary  минимум, потом обратно развернуть в коллекцию, либо через reduce, либо через collect. Но как именно, пока не знаю.

2024-12-03 23:30 UTC, MVBelyaev78 commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +                .sorted(Comparator.comparing(Employee::getCodeDepartment).thenComparing(Employee::getFullName))
Понял, повторю материал по Map и буду делать в этом направлении.

2024-12-04 17:43 UTC, isavinov requested changes

2024-12-04 17:43 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/controller/DepartmentController.java
> +    private final Department department = new Department(TestDepartment.createData());
В идеале - он не должен вызываться совсем. Это как-то не очень правильно наполнять продакшн-реди код тестовыми данными, они должны наполняться реальными с помощью вызовов методов контроллера. Но понимаю, что тестовые данные иметь хочется, чтобы с каждым рестартом приложения не добавлять их заново - в этом случае самое правильное решение будет наполнить коллекцию сотрудниками прям непосредственно в конструкторе класса Department (который должен называться DepartmentService)

2024-12-04 17:43 UTC, isavinov commented on src/main/java/pro/sky/hw_2024_11_11/service/Department.java
> +        if (resultOptional.isPresent()) {
Да в целом все просто, метод мап не нужен - прогоняем сотрудников и сравниваем их зарпрлаты. Только в примере свое исключение проставь 
```
public Employee getLowestPaidEmployee() {
        return arrEmployee
                .stream()
                .min(Comparator.comparingInt(Employee::getSalary))
                .orElseThrow(() -> new RuntimeException());
    }
```

2024-12-06 11:52 UTC, merged